[package]
name = "bitenum"
description = "bitflags enum"
keywords = ["enum", "bitflags", "no_std"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/mixkorshun/bitenum"
repository = "https://github.com/mixkorshun/bitenum"
edition = "2021"

[dependencies]
